name: fsek_mobile
description: Mobile application for the F-guild

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#

version: 1.4.6122+1 #buildnumber incremented automatically in codemagic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.0.0 # required for flutter master branch 2020-08-04
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2
  provider: ^6.0.0 # For Blocs and more
  http: ^0.13.3 # For Http requests
  json_annotation: ^4.0.1 # For json serializing
  flutter_secure_storage: ^6.0.0 # For storing encryption keys for Boxes
  shared_preferences: ^2.0.6 # For web storage as well as small things, such as app theme
  firebase_messaging: ^12.0.0 # For Push notifications
  firebase_core: ^1.0.0
  equatable: ^2.0.3 # For State
  bloc: ^7.0.0 # For State
  flutter_bloc: ^7.0.1 # For State
  intl: ^0.17.0 # For Internationalization (not used yet)
  package_info: ^2.0.2 # For getting version number
  get_it: ^7.1.4 # For singleton service instances
  location_permissions: ^4.0.0 # For requesting location permissions
  table_calendar: ^3.0.1 # For calender
  url_launcher: ^6.0.9 # For memes
  action_cable: ^1.2.0 # For messaging
  infinite_scroll_pagination: 3.1.0 # For messaging
  linkable: ^3.0.1 # For making numbers, emails and links clickable
  flutter_html: ^2.1.1 # For rendering HTMLq
  pull_to_refresh: ^2.0.0 # this already exists in flutter
  flutter_local_notifications: ^8.1.1 # For handling local notifications
  flutter_math_fork: ^0.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  json_serializable: ^4.1.3 # For Data serialization
  build_runner: ^2.0.5 # For building the JSON data object
  flutter_launcher_icons: ^0.9.0 # For easily building launch icons
  # The 4 below are for unit and integration testing

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/icon-512.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class. 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/
   - assets/img/memes/
   - assets/img/moose_game/
   - assets/data/guide/


  fonts:
   - family: Brandon Grotesque
     fonts:
      - asset: assets/BrandonGrotesque-Regular.ttf
   - family: VT323
     fonts:
      - asset: assets/VT323-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
